In [235]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns
from termcolor import colored
from sklearn.dummy import DummyClassifier 
from sklearn.metrics import accuracy_score

In [4]:
df = pd.read_hdf("adult.h5")

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 32561 entries, 0 to 32560
Data columns (total 15 columns):
Age               32561 non-null int8
Workclass         30725 non-null object
fnlwgt            32561 non-null int64
Education         32561 non-null object
Education-Num     32561 non-null int64
Martial Status    32561 non-null object
Occupation        30718 non-null object
Relationship      32561 non-null object
Race              32561 non-null object
Sex               32561 non-null bool
Capital Gain      32561 non-null int16
Capital Loss      32561 non-null int16
Hours per week    32561 non-null int8
Country           31978 non-null object
Target            32561 non-null object
dtypes: bool(1), int16(2), int64(2), int8(2), object(8)
memory usage: 2.9+ MB


In [6]:
df.head()

Age         Workclass  fnlwgt  Education  Education-Num  \
0   39         State-gov   77516  Bachelors             13   
1   50  Self-emp-not-inc   83311  Bachelors             13   
2   38           Private  215646    HS-grad              9   
3   53           Private  234721       11th              7   
4   28           Private  338409  Bachelors             13   

       Martial Status         Occupation   Relationship   Race    Sex  \
0       Never-married       Adm-clerical  Not-in-family  White   True   
1  Married-civ-spouse    Exec-managerial        Husband  White   True   
2            Divorced  Handlers-cleaners  Not-in-family  White   True   
3  Married-civ-spouse  Handlers-cleaners        Husband  Black   True   
4  Married-civ-spouse     Prof-specialty           Wife  Black  False   

   Capital Gain  Capital Loss  Hours per week        Country Target  
0          2174             0              40  United-States  <=50K  
1             0             0              13  United-States  <=50K  
2             0             0              40  United-States  <=50K  
3             0             0              40  United-States  <=50K  
4             0             0              40           Cuba  <=50K

In [8]:
df.columns.values

array(['Age', 'Workclass', 'fnlwgt', 'Education', 'Education-Num',
       'Martial Status', 'Occupation', 'Relationship', 'Race', 'Sex',
       'Capital Gain', 'Capital Loss', 'Hours per week', 'Country',
       'Target'], dtype=object)

Race              1
Education         1
Martial Status    1
Age               1
Country           1
Sex               1
Occupation        1
Relationship      1
Workclass         1
Capital Loss      1
Capital Gain      1
Education-Num     1
Target            1
fnlwgt            1
Hours per week    1
dtype: int64

In [66]:
pd.set_option('display.max_colwidth', -1)


In [18]:
df.columns


Index(['Age', 'Workclass', 'fnlwgt', 'Education', 'Education-Num',
       'Martial Status', 'Occupation', 'Relationship', 'Race', 'Sex',
       'Capital Gain', 'Capital Loss', 'Hours per week', 'Country', 'Target'],
      dtype='object')

In [20]:
df.sample(15)

Age    Workclass  fnlwgt     Education  Education-Num  \
17596  55   Private      226875  HS-grad       9               
25415  36   Private      126954  HS-grad       9               
23260  37   Private      178948  Bachelors     13              
25975  42   Private      297335  Assoc-acdm    12              
19635  37   Private      167415  Prof-school   15              
19722  38   Local-gov    86643   Bachelors     13              
3707   41   Private      113555  Some-college  10              
11434  46   Private      247043  HS-grad       9               
22191  27   Private      38606   Bachelors     13              
27024  61   Private      280088  7th-8th       4               
8676   27   Private      199903  Bachelors     13              
15696  18   NaN          151463  11th          7               
21551  41   Federal-gov  153132  Bachelors     13              
8159   27   Local-gov    74056   Bachelors     13              
20093  26   Private      164488  Masters       14              

              Martial Status         Occupation    Relationship  \
17596  Married-civ-spouse     Sales              Husband          
25415  Divorced               Transport-moving   Not-in-family    
23260  Married-civ-spouse     Exec-managerial    Wife             
25975  Married-spouse-absent  Exec-managerial    Unmarried        
19635  Married-civ-spouse     Prof-specialty     Husband          
19722  Married-civ-spouse     Prof-specialty     Husband          
3707   Married-civ-spouse     Craft-repair       Husband          
11434  Married-civ-spouse     Transport-moving   Husband          
22191  Never-married          Sales              Not-in-family    
27024  Divorced               Machine-op-inspct  Unmarried        
8676   Never-married          Prof-specialty     Not-in-family    
15696  Never-married          NaN                Other-relative   
21551  Married-civ-spouse     Prof-specialty     Husband          
8159   Never-married          Tech-support       Not-in-family    
20093  Married-civ-spouse     Prof-specialty     Husband          

                     Race    Sex  Capital Gain  Capital Loss  Hours per week  \
17596  White               True   4064          0             40               
25415  White               True   0             0             40               
23260  White               False  7688          0             45               
25975  Asian-Pac-Islander  False  0             0             31               
19635  White               True   0             0             60               
19722  White               True   0             0             45               
3707   Amer-Indian-Eskimo  True   7298          0             50               
11434  White               True   0             0             40               
22191  White               True   0             1504          45               
27024  White               False  0             0             40               
8676   White               False  0             0             40               
15696  White               True   0             0             7                
21551  White               True   0             0             38               
8159   White               True   0             0             50               
20093  White               True   0             1887          40               

             Country Target  
17596  United-States  <=50K  
25415  United-States  <=50K  
23260  United-States  >50K   
25975  Laos           <=50K  
19635  United-States  >50K   
19722  United-States  >50K   
3707   United-States  >50K   
11434  United-States  >50K   
22191  United-States  <=50K  
27024  United-States  <=50K  
8676   United-States  <=50K  
15696  United-States  <=50K  
21551  United-States  >50K   
8159   United-States  <=50K  
20093  United-States  >50K

In [21]:
if 'fnlwgt' in df: del df['fnlwgt']

In [22]:
df.head()

Age         Workclass  Education  Education-Num      Martial Status  \
0  39   State-gov         Bachelors  13             Never-married        
1  50   Self-emp-not-inc  Bachelors  13             Married-civ-spouse   
2  38   Private           HS-grad    9              Divorced             
3  53   Private           11th       7              Married-civ-spouse   
4  28   Private           Bachelors  13             Married-civ-spouse   

          Occupation   Relationship   Race    Sex  Capital Gain  Capital Loss  \
0  Adm-clerical       Not-in-family  White  True   2174          0              
1  Exec-managerial    Husband        White  True   0             0              
2  Handlers-cleaners  Not-in-family  White  True   0             0              
3  Handlers-cleaners  Husband        Black  True   0             0              
4  Prof-specialty     Wife           Black  False  0             0              

   Hours per week        Country Target  
0  40              United-States  <=50K  
1  13              United-States  <=50K  
2  40              United-States  <=50K  
3  40              United-States  <=50K  
4  40              Cuba           <=50K

In [23]:
df.shape

(32561, 14)

In [148]:
for column in df.columns:
    print(colored("Unique value: {0}".format(column),'blue',attrs=['bold','blink','underline']))
    print(df[column].unique())

Unique value: Age
[39 50 38 53 28 37 49 52 31 42 30 23 32 40 34 25 43 54 35 59 56 19 20 45
 22 48 21 24 57 44 41 29 18 47 46 36 79 27 67 33 76 17 55 61 70 64 71 68
 66 51 58 26 60 90 75 65 77 62 63 80 72 74 69 73 81 78 88 82 83 84 85 86
 87]
Unique value: Workclass
['State-gov' 'Self-emp-not-inc' 'Private' 'Federal-gov' 'Local-gov' nan
 'Self-emp-inc' 'Without-pay' 'Never-worked']
Unique value: Education
['Bachelors' 'HS-grad' '11th' 'Masters' '9th' 'Some-college' 'Assoc-acdm'
 'Assoc-voc' '7th-8th' 'Doctorate' 'Prof-school' '5th-6th' '10th'
 '1st-4th' 'Preschool' '12th']
Unique value: Education-Num
[13  9  7 14  5 10 12 11  4 16 15  3  6  2  1  8]
Unique value: Martial Status
['Never-married' 'Married-civ-spouse' 'Divorced' 'Married-spouse-absent'
 'Separated' 'Married-AF-spouse' 'Widowed']
Unique value: Occupation
['Adm-clerical' 'Exec-managerial' 'Handlers-cleaners' 'Prof-specialty'
 'Other-service' 'Sales' 'Craft-repair' 'Transport-moving'
 'Farming-fishing' 'Machine-op-inspct' 'Te

In [166]:
for repet in df.columns:
    print (colored("\nRecurring values: {0}\n".format(repet),'green',attrs=['bold','blink','underline']))
    print(df[repet].value_counts())


Recurring values: Age

36    898
31    888
34    886
23    877
35    876
33    875
28    867
30    861
37    858
25    841
27    835
32    828
38    827
39    816
29    813
41    808
24    798
40    794
26    785
42    780
43    770
22    765
20    753
46    737
45    734
44    724
21    720
19    712
47    708
50    602
51    595
49    577
18    550
48    543
52    478
53    464
55    419
54    415
17    395
58    366
56    366
57    358
59    355
60    312
61    300
62    258
63    230
64    208
65    178
67    151
66    150
68    120
69    108
70     89
71     72
72     67
73     64
74     51
76     46
75     45
90     43
77     29
78     23
80     22
79     22
81     20
82     12
84     10
83      6
85      3
88      3
87      1
86      1
Name: Age, dtype: int64

Recurring values: Workclass

Private             22696
Self-emp-not-inc     2541
Local-gov            2093
State-gov            1298
Self-emp-inc         1116
Federal-gov           960
Without-pay            14
Never-work

In [108]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 32561 entries, 0 to 32560
Data columns (total 14 columns):
Age               32561 non-null int8
Workclass         30725 non-null object
Education         32561 non-null object
Education-Num     32561 non-null int64
Martial Status    32561 non-null object
Occupation        30718 non-null object
Relationship      32561 non-null object
Race              32561 non-null object
Sex               32561 non-null bool
Capital Gain      32561 non-null int16
Capital Loss      32561 non-null int16
Hours per week    32561 non-null int8
Country           31978 non-null object
Target            32561 non-null object
dtypes: bool(1), int16(2), int64(1), int8(2), object(8)
memory usage: 2.7+ MB


In [165]:
df['Education-Num'].unique()

array([13,  9,  7, 14,  5, 10, 12, 11,  4, 16, 15,  3,  6,  2,  1,  8],
      dtype=int64)

In [172]:
df['Education-Num'] = df['Education-Num'].astype('int8')


array([13,  9,  7, 14,  5, 10, 12, 11,  4, 16, 15,  3,  6,  2,  1,  8],
      dtype=int64)

array([13,  9,  7, 14,  5, 10, 12, 11,  4, 16, 15,  3,  6,  2,  1,  8],
      dtype=int64)

In [216]:
df[ df['Workclass'].isnull() ].shape

(1836, 16)

In [179]:
df['Sex_cat'] = df['Sex'].astype(np.int8)

In [205]:
df['Target_cat'] = df['Target'].map(lambda x: int(x == '<=50K') )  

In [206]:
df.head(10)

Age         Workclass  Education  Education-Num         Martial Status  \
0   39         State-gov  Bachelors             13          Never-married   
1   50  Self-emp-not-inc  Bachelors             13     Married-civ-spouse   
2   38           Private    HS-grad              9               Divorced   
3   53           Private       11th              7     Married-civ-spouse   
4   28           Private  Bachelors             13     Married-civ-spouse   
5   37           Private    Masters             14     Married-civ-spouse   
6   49           Private        9th              5  Married-spouse-absent   
7   52  Self-emp-not-inc    HS-grad              9     Married-civ-spouse   
8   31           Private    Masters             14          Never-married   
9   42           Private  Bachelors             13     Married-civ-spouse   

          Occupation   Relationship   Race    Sex  Capital Gain  Capital Loss  \
0       Adm-clerical  Not-in-family  White   True          2174             0   
1    Exec-managerial        Husband  White   True             0             0   
2  Handlers-cleaners  Not-in-family  White   True             0             0   
3  Handlers-cleaners        Husband  Black   True             0             0   
4     Prof-specialty           Wife  Black  False             0             0   
5    Exec-managerial           Wife  White  False             0             0   
6      Other-service  Not-in-family  Black  False             0             0   
7    Exec-managerial        Husband  White   True             0             0   
8     Prof-specialty  Not-in-family  White  False         14084             0   
9    Exec-managerial        Husband  White   True          5178             0   

   Hours per week        Country Target  Sex_cat  Target_cat  
0              40  United-States  <=50K        1           1  
1              13  United-States  <=50K        1           1  
2              40  United-States  <=50K        1           1  
3              40  United-States  <=50K        1           1  
4              40           Cuba  <=50K        0           1  
5              40  United-States  <=50K        0           1  
6              16        Jamaica  <=50K        0           1  
7              45  United-States   >50K        1           0  
8              50  United-States   >50K        0           0  
9              40  United-States   >50K        1           0

In [207]:
df.corr()

Age  Education-Num       Sex  Capital Gain  Capital Loss  \
Age             1.000000       0.036527  0.088832      0.064301      0.057775   
Education-Num   0.036527       1.000000  0.012280      0.062300      0.079923   
Sex             0.088832       0.012280  1.000000      0.028219      0.045567   
Capital Gain    0.064301       0.062300  0.028219      1.000000     -0.027282   
Capital Loss    0.057775       0.079923  0.045567     -0.027282      1.000000   
Hours per week  0.068756       0.148123  0.229309      0.031964      0.054256   
Sex_cat         0.088832       0.012280  1.000000      0.028219      0.045567   
Target_cat     -0.234037      -0.335154 -0.215980     -0.154853     -0.150526   

                Hours per week   Sex_cat  Target_cat  
Age                   0.068756  0.088832   -0.234037  
Education-Num         0.148123  0.012280   -0.335154  
Sex                   0.229309  1.000000   -0.215980  
Capital Gain          0.031964  0.028219   -0.154853  
Capital Loss          0.054256  0.045567   -0.150526  
Hours per week        1.000000  0.229309   -0.229689  
Sex_cat               0.229309  1.000000   -0.215980  
Target_cat           -0.229689 -0.215980    1.000000

In [217]:
df.fillna(-1).info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 32561 entries, 0 to 32560
Data columns (total 16 columns):
Age               32561 non-null int8
Workclass         32561 non-null object
Education         32561 non-null object
Education-Num     32561 non-null int8
Martial Status    32561 non-null object
Occupation        32561 non-null object
Relationship      32561 non-null object
Race              32561 non-null object
Sex               32561 non-null bool
Capital Gain      32561 non-null int16
Capital Loss      32561 non-null int16
Hours per week    32561 non-null int8
Country           32561 non-null object
Target            32561 non-null object
Sex_cat           32561 non-null int8
Target_cat        32561 non-null int64
dtypes: bool(1), int16(2), int64(1), int8(4), object(8)
memory usage: 4.0+ MB


Age         Workclass  Education  Education-Num      Martial Status  \
0   39         State-gov  Bachelors             13       Never-married   
1   50  Self-emp-not-inc  Bachelors             13  Married-civ-spouse   
2   38           Private    HS-grad              9            Divorced   
3   53           Private       11th              7  Married-civ-spouse   
4   28           Private  Bachelors             13  Married-civ-spouse   

          Occupation   Relationship   Race    Sex  Capital Gain  Capital Loss  \
0       Adm-clerical  Not-in-family  White   True          2174             0   
1    Exec-managerial        Husband  White   True             0             0   
2  Handlers-cleaners  Not-in-family  White   True             0             0   
3  Handlers-cleaners        Husband  Black   True             0             0   
4     Prof-specialty           Wife  Black  False             0             0   

   Hours per week        Country Target  Sex_cat  Target_cat  
0              40  United-States  <=50K        1           1  
1              13  United-States  <=50K        1           1  
2              40  United-States  <=50K        1           1  
3              40  United-States  <=50K        1           1  
4              40           Cuba  <=50K        0           1

In [219]:
cat_feats = df.select_dtypes(include=[np.object]).columns

In [223]:
cat_feats

Index(['Workclass', 'Education', 'Martial Status', 'Occupation',
       'Relationship', 'Race', 'Country', 'Target'],
      dtype='object')

In [225]:
for feats in cat_feats:
     df["{}_cat".format(feats)] =pd.factorize(df[feats])[0]

In [226]:
df.head()

Age         Workclass  Education  Education-Num      Martial Status  \
0   39         State-gov  Bachelors             13       Never-married   
1   50  Self-emp-not-inc  Bachelors             13  Married-civ-spouse   
2   38           Private    HS-grad              9            Divorced   
3   53           Private       11th              7  Married-civ-spouse   
4   28           Private  Bachelors             13  Married-civ-spouse   

          Occupation   Relationship   Race    Sex  Capital Gain  ...  Target  \
0       Adm-clerical  Not-in-family  White   True          2174  ...   <=50K   
1    Exec-managerial        Husband  White   True             0  ...   <=50K   
2  Handlers-cleaners  Not-in-family  White   True             0  ...   <=50K   
3  Handlers-cleaners        Husband  Black   True             0  ...   <=50K   
4     Prof-specialty           Wife  Black  False             0  ...   <=50K   

   Sex_cat Target_cat Workclass_cat  Education_cat  Martial Status_cat  \
0        1          0             0              0                   0   
1        1          0             1              0                   1   
2        1          0             2              1                   2   
3        1          0             2              2                   1   
4        0          0             2              0                   1   

   Occupation_cat  Relationship_cat  Race_cat  Country_cat  
0               0                 0         0            0  
1               1                 1         0            0  
2               2                 0         0            0  
3               2                 1         1            0  
4               3                 2         1            1  

[5 rows x 23 columns]

In [237]:
X = df[['Age']].values
y= df["Target_cat"].values

model = DummyClassifier()
model.fit(X,y)
y_pred = model.predict(X)
accuracy_score(y_pred,y)

0.6313995270415528

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)